CREATE TABLE owners (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    birthday VARCHAR(50)
);

CREATE TABLE cats (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    birthday VARCHAR(50),
    breed VARCHAR(100),
    color VARCHAR(50),
    owner_id INT,
    CONSTRAINT fk_owner
        FOREIGN KEY (owner_id)
        REFERENCES owners(id)
        ON DELETE SET NULL
);

CREATE TABLE friends (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255),
    cat_id INT NOT NULL,
    second_cat_id INT NOT NULL,
    CONSTRAINT fk_cat
        FOREIGN KEY (cat_id)
        REFERENCES cats(id)
        ON DELETE CASCADE,
    CONSTRAINT fk_second_cat
        FOREIGN KEY (second_cat_id)
        REFERENCES cats(id)
        ON DELETE CASCADE
);